### ISSUE TITLE
Submission guidelines?

### ISSUE THREAD

**Issue by rootulp** [bccss/iprep#2]
How do you want students to submit answers to questions? @louisandrews @jayelm

**Comment by jayelm** [comment]
Likely through code snippets submitted on the Slack group. Maybe later we'll introduce some kind of github system.

**Comment by rootulp** [comment]
Using GitHub branches could be beneficial for students to view and contribute to other answers. Also would be good Git experience but I understand if you want to introduce this later.

**Comment by jayelm** [comment]
For sure. Maybe both - encourage people to create a github repository with iprep solutions, and then submit links to the slack group or something

**Comment by rootulp** [comment]
Sounds good. We can revisit this later.
